apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy21
  labels:
    app: autodeploy21
  namespace: namespace-workflow-1708343180718
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy21
  template:
    metadata:
      labels:
        app: autodeploy21
    spec:
      containers:
        - name: autodeploy21
          image: acrworkflow1708343180718.azurecr.io/image-workflow-1708343180718:latest
          ports:
            - containerPort: 5000